# Use an official Maven image to build the app
FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package

# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/tasklist-0.0.1-SNAPSHOT.war ./tasklist-0.0.1-SNAPSHOT.war

# Expose port 8080 (or any port your app runs on)
EXPOSE 8080

# Run the app
CMD ["java", "-Dserver.port=${PORT}", "-jar", "tasklist-0.0.1-SNAPSHOT.war"]
