services:
type: web
name: probook_20240706
env: docker
dockerfilePath: ./tasklist/dockerfile
branch: main
buileCommand: ./mvnw clean package
startCommand: java -Dserver.port=$PORT -jar target/tasklist